name: Swift ARM

on: [push]

jobs:

    linux-swift-armv7-debian-build:
        name: Debian Armv7 (Build)
        runs-on: ubuntu-20.04
        container: colemancda/swift-armv7:amd64-prebuilt
        steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Swift Version
          run: swift --version
        - name: Build
          run: |
            cd /usr/src/swift-armv7
            export SWIFT_PACKAGE_SRCDIR=$GITHUB_WORKSPACE
            export SWIFT_PACKAGE_BUILDDIR=$SWIFT_PACKAGE_SRCDIR/.build
            mkdir -p $SWIFT_PACKAGE_BUILDDIR
            mkdir -p /usr/src/swift-armv7/build/
            ./generate-swiftpm-toolchain.sh
            ./build-swift-package.sh
        - name: Archive Build artifacts
          uses: actions/upload-artifact@v3
          with:
            name: swiftpm-build-debian-armv7
            path: .build/*
