name: Swift ARM
on: [push]
jobs:

    linux-armv7-crosscompile-build:
        name: Crosscompile for Linux Armv7
        runs-on: ubuntu-latest
        container: colemancda/swift-armv7:latest-prebuilt
        steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Swift Version
          run: swift --version
        - name: Build (Release)
          run: |
            cd $SRC_ROOT
            export SWIFT_PACKAGE_SRCDIR=$GITHUB_WORKSPACE
            export SWIFT_PACKAGE_BUILDDIR=$SWIFT_PACKAGE_SRCDIR/.build
            $SRC_ROOT/build-swift-package.sh
        - name: Archive Build artifacts
          uses: actions/upload-artifact@v3
          with:
            name: linux-armv7-crosscompile
            path: .build/*/solartool

    linux-swift-arm64:
              name: Linux ARM64
              runs-on: [self-hosted, linux, ARM64]
              container:
                image: swift:5.10-jammy
              steps:
              - name: Checkout
                uses: actions/checkout@v1
              - name: Build (Release)
                run: swift build -c release
              - name: Upload build artifacts
                uses: actions/upload-artifact@v2
                with:
                  name: build-linux-arm64
                  path: ".build/aarch64-unknown-linux-gnu/release/solartool"
